### ISSUE TITLE
xhyve: deadlock while loading Hermit app

### ISSUE THREAD

**Issue by stv0g** [RWTH-OS/HermitCore#15]
I've been playing around with the new [xhyve](http://www.xhyve) Hypervisor for OS X.

I managed to boot into the Kernel and mounting the new 9P share from my OS X host.
Unfortunately it crashed while loading a Hermit app.

```
Welcome to HermitCore (http://www.hermitcore.org/)!
/ # /hermit/tools/proxy /hermit/usr/tests/hello 1
smpboot: CPU 1 is now offline
INFO: rcu_sched detected stalls on CPUs/tasks:
    1: (0 ticks this GP) idle=191/140000000000000/0 softirq=2786/2786 fqs=0
    (detected by 0, t=5252 jiffies, g=-245, c=-246, q=0)
Task dump for CPU 1:
swapper/1       R  running task        0     0      1 0x00200000
 ffff88013aacfeb8 0000000000000000 ffff88013aacc000 ffff88013aacc000
 ffff88013aacc000 ffffffff810c78a6 0000000000000000 ffffffff81055c6a
 0000000000000286 ffffffff8106f862 ffffffff813d6198 ffffffff8123c461
Call Trace:
 [<ffffffff810c78a6>] ? 0xffffffff810c78a6
 [<ffffffff81055c6a>] ? 0xffffffff81055c6a
 [<ffffffff8106f862>] ? 0xffffffff8106f862
 [<ffffffff8123c461>] ? 0xffffffff8123c461
 [<ffffffff8102769f>] ? 0xffffffff8102769f
 [<ffffffff810614e6>] ? 0xffffffff810614e6
rcu_sched kthread starved for 5252 jiffies! g18446744073709551371 c18446744073709551370 f0x0
```

**Comment by stv0g** [comment]
I extended the Makefile to boot xhyve b555c45024420e722aad6602fa69d9147da52f1c.

xhyve is a really lightweight hypervisor because it makes use of Apples Hypervisor Framework of OS X 10.10.

You need a patched version: https://github.com/stv0g/xhyve/tree/virtio-9p

**Comment by stlankes** [comment]
I know xhyve and already used it. I will check the problem and try to find a solution.

**Comment by stv0g** [comment]
> I know xhyve and already used it. I will check the problem and try to find a solution.

Nice :-)

It seems like xhyve does not emulate NUMA nodes like QEmu is doing.
Maybe HermitCore fails there?

**Comment by stlankes** [comment]
No this is not the problem. On a UMA system you will see one isle.

I think that HermitCore read from a MSR, which isn't the available on older cpus / on xhyve.

**Comment by stlankes** [comment]
@stv0g : Could you test the current branch `devel`? Maybe I solved the problem...

**Comment by stv0g** [comment]
Thanks, I will test in a couple of days.
Building Linux on OS X is somehow cumbersome...

**Comment by stlankes** [comment]
No stress, take your time

**Comment by stlankes** [comment]
I close this issue because I don't use xhyve. Do we have xhyve users?
