### ISSUE TITLE
Why is init.asm not linked into libhermit.a?

### ISSUE THREAD

**Issue by stv0g** [RWTH-OS/HermitCore#19]
Currently the x86 boot code is compiled into the Linux kernel and [copied to `hermit_trampoline`](https://github.com/stv0g/linux/blob/hermit-boot/arch/x86/hermit/hermit.c#L174) during the start of a Hermit app.

I don't see a reason, why we can not directly link it into the ELF binary of a Hermit app or libhermit.a

Irrespective of this, I moved `init.asm` to the Linux repo, renamed it `boot.asm` and integrated into the kbuild system. If it's only used by the kernel, we also should build it there.

See: stv0g/linux@21e290d9079999ea586c45ebd339f94c380c95c7

**Comment by stlankes** [comment]
It is only a backup of my trampoline code, which I used to jump from 16bit over 32bit into 64bit mode. It is indirectly integrated in the Linux code, where I use the code as string to boot HermitCore on a specific processor.

**Comment by stv0g** [comment]
Ah okay. Is there a reason that the trampoline code is not part of libhermit.a?

Do you want me to submit a PR to integrate the code into the kbuild system?
Adding it to Linux repo makes more sense to me.

**Comment by stlankes** [comment]
A x86 processor starts in 16bit mode. Consequently, we have no paging, no virtual address space and the (physical) start address must be below 1MB. Bad idea to start more than one kernel.

Yes, the integration of the trampoline code has to be in the build system. The wrong location has more historical reasons. I want to migrate the code.

**Comment by stlankes** [comment]
Close issue because I merged stv0g/linux@21e290d
