### ISSUE TITLE
fopen("file.name", "w") cannot create new file

### ISSUE THREAD

**Issue by daniel-k** [RWTH-OS/HermitCore#22]
Xray is using `f = fopen(filename, "w");` to save it's reports. If the given file does not exists, it should be created, refer [man fopen](http://www.skrenta.com/rt/man/fopen.3.html):

```
w      Truncate  file  to  zero length or create text file
       for writing.   The  stream  is  positioned  at  the
       beginning of the file.
```

However, this doesn't work in the sense that no file is created and `fopen()` returns `NULL`.

**Comment by stlankes** [comment]
The the [last commit](https://github.com/RWTH-OS/HermitCore/commit/ed81a44b8c4f94da5b18fb905abc3a3dee6ffdeb) should solve the problem. The definitions in `fcntl.h` were wrong. Please rebuild _newlib_ and test the patch.

**Comment by daniel-k** [comment]
ed81a44b8c4f indeed fixed this issue. Awesome! Thanks for addressing it this quickly, I'm closing this now.
