### ISSUE TITLE
Syscall redirection (I/O) slow

### ISSUE THREAD

**Issue by daniel-k** [RWTH-OS/HermitCore#24]
Now that I'm using XRay for profiling and debugging I'm often transfer quite a lot of data from my application that is being profiled to the Linux system (and ultimately to my host system through p9 mount).

The reports can easily be of several Megabytes and transfering them is **really** slow. I'm seeing transfer speeds of 20 KiB/s right now. Is there anything we can do to speed this up? The present rate appears to be quite low anyway.

**Comment by stlankes** [comment]
Hm, you could increase the macro MEM_SIZE in [src/include/lwipopts.h](https://github.com/RWTH-OS/LwIP/blob/630df185f1bc02e1c32f3d12251f6a55d77c6324/src/include/lwipopts.h), which defines the size of the heap memory. A lot of data requires also a lot of memory.

**Comment by stv0g** [comment]
The host-shared P9 mount is based on virtio. I doubt that this is the bottleneck.

**Comment by stlankes** [comment]
Yes, this should be the bottleneck. I forgot the P9 interface. @daniel-k Should we close this issue?

**Comment by daniel-k** [comment]
@stlankes I'm not sure if you have read @stv0g's post correctly. I think he wanted to state that P9 is *not* the bottleneck :smiley:

**Comment by stlankes** [comment]
Oh, I miss understood  stv0g. Ok, will test it.

**Comment by stlankes** [comment]
Hello daniel-k, I close the issue. We will solve this problem with uhyve soon.
