### ISSUE TITLE
Provide a docker image/deb/rpm/...

### ISSUE THREAD

**Issue by jbreitbart** [RWTH-OS/HermitCore#36]
Building HermitCore from scratch takes quite long. Providing pre-built binaries would be useful for everyone who would like to just give it a try. An (seemingly) easy way to do this is https://bintray.com/ as it integrates with Travis https://docs.travis-ci.com/user/deployment/bintray

**Comment by stlankes** [comment]
Through the great help of @daniel-k, we are able create deb packages. This was more work than I thought. Please check if you are able to use on your system. With following commands you are able to install HermitCore on you system:

```
echo "deb https://dl.bintray.com/rwth-os/hermitcore vivid main" | sudo tee -a /etc/apt/sources.list
sudo apt-get -qq update
sudo apt-get install binutils-hermit newlib-hermit pthread-embedded-hermit gcc-hermit
```

Afterwards you will find the cross-compiler at /opt/hermit/bin

Have fun!

**Comment by jbreitbart** [comment]
Thanks. Looks good. :+1:
