### ISSUE TITLE
HermitCore needs a logo

### ISSUE THREAD

**Issue by stv0g** [RWTH-OS/HermitCore#71]
I want to put HermitCore onto the OSS listing at: http://fine-aachen.rwth-aachen.de/projects/

**Comment by stlankes** [comment]
Hm, do you have an idea? Sometimes I use a hermit as logo. Do you have an better idea?

**Comment by stv0g** [comment]
I think a hermit is a nice idea 👍

**Comment by stlankes** [comment]
Do you like it?

![1f980](https://user-images.githubusercontent.com/5888473/27185365-5fbf9d0a-51e5-11e7-88c3-f8afcf478aaa.png)

**Comment by stv0g** [comment]
Yes :-) Thats good! Should I add it to the repo & fein-aachen.org?

**Comment by stlankes** [comment]
I take the logo from https://www.gfxmag.com/crab-emoji-vector-icon/ 

> Emojis provided free by EmojiOne Attribution 4.0 International (CC BY 4.0)

I think that we are able to use it.

**Comment by stv0g** [comment]
I added to logo to:
- hermitcore.org
- fein-aachen.org
- the README
