### ISSUE TITLE
Page within heap area also belongs to page table

### ISSUE THREAD

**Issue by olivierpierre** [RWTH-OS/HermitCore#83]
The page at virtual address `0x3FE00000` is located within the heap area. However, according to the way page tables are defined, the virtual page at this specific address belongs to the page table: it is mapped on the same physical page as the virtual page at `0x802000` (PDPT).

Thus, when an application allocate some memory with malloc, gets the page at `0x3FE00000`, and tries to write to it, it overwrites the PDPT, leading to random behavior (mostly crash). Here is a program that triggers the issue:

```C
#include <stdio.h>
#include <stdlib.h>

/* This should be sufficient to push the break past 0x3FE00000 */
#define BUFFER_SIZE	(1024 * 1024 * 1024)
#define ADDR_ISSUE	0x3FE00000

int main(void) {
	char *buffer;
	int i;

	/* Increases the break */
	buffer = malloc(BUFFER_SIZE);

	/* Actually map memory and write in it */
	for(i=0; i<BUFFER_SIZE; i++) {
		if(&(buffer[i]) == (void *)ADDR_ISSUE)
			printf("Writing in %p\n", ADDR_ISSUE);
		buffer[i] = '\0';
	}

	/* The bug makes that this should not be executed: */
	printf("Successfully allocated and mapped %llu bytes\n", BUFFER_SIZE);

	return 0;
}
```
With uhyve, the VM exists and KVM receives a shutdown signal. With qemu or qemu/kvm, the VM hangs. I guess the reason we do not get a page fault here is that the first entry of the PDPT at `0x802000` is mapping a large part of the address space, including the page fault handler, and this large area gets unmapped when something is written at `0x3FE00000`.

One hacky solution I found is to move the start of the heap past that address, in `include/hermit/stddef.h`:
```C
#define HEAP_START	(PAGE_2M_CEIL((size_t)&kernel_start + image_size + 0x3fe00000) + 4*PAGE_SIZE)
```

**Comment by stv0g** [comment]
Hi Oliver, are referring to a 32 or 64 bit build? In 64 bit builds the page tables should be located at the end of the 64 bit Adress space.

I can't really explain how this calculation of the heap start Adress is done. But to me it looks a bit strange.

Cheers

**Comment by olivierpierre** [comment]
Hi, thank you for your reply. This is a 64 bit build. I can see that the self-referencing page tables are built in a way that it is easy to access them using addresses such as `0xFFFFFF8000000000`.

However, as far as I understand, with these page tables built as such, the last entry in the page directory points back to the PML4. Here is what happens when translating virtual address `0x3FE00000`:

```
+----+
|cr3 |
+----+      PML4 @0x801000        A.     PDPT @0x802000         B.    PD @0x803000
  +-------->------------------+     ---->------------------+     ---->------------------+
   +------->+0x802027         +-----+    |0x803023         +-----+    |0x804023         |
   |        +-----------------+          +-----------------+          +-----------------+
   |        |                 |          |                 |          |                 |
   |        |                 |          |                 |          |                 |
   |        |                 |          |                 |          |                 |
   |        |                 |          |                 |          |                 |
   |        |                 |          |                 |          |                 |
   |        |                 |          |                 |          |                 |
   |        |                 |          |                 |          |                 |
   |        +-----------------+          +-----------------+          +-----------------+
   |        |0x801223         |          |0x801223         |          |0x801223         +---+
   |        +-----------------+          +-----------------+          +-----------------+   | C.
   |                                                                                        |
   |                                                                                        |
   +----------------------------------------------------------------------------------------+
```
With this specific address, we go to the last entry in the page directory and use the first entry of the PML4 as a page table entry. Thus, the physical address mapped by `0x3FE00000` is actually `0x802000` which is a PDPT page.

When the application allocates a lot of dynamic memory, the break goes past `0x3FE00000` and the application will eventually try to access the page. Normally, it should page fault and triggers the on-demand mapping for a heap page. However, with `0x3FE00000`, the corresponding virtual page is already mapped to `0x802000` so an application writing to `0x3FE00000` is overwriting the PDPT.

You can confirm it with this simple program:

```
#include <stdio.h>

extern size_t virt_to_phys(size_t addr);

int main(void) {
	size_t phys = virt_to_phys(0x3fe00000);
	printf("0x%x -> 0x%x\n", 0x3fe00000, phys);
	return 0;
}
```

It will show that `0x3FE00000` is mapped to `0x802000`.

**Comment by stlankes** [comment]
Hello Pierre,

I think that this was bug in my startup code (entry.asm). I already fixed in the branch `devel`. Could you test if this solves your problems?

Cheers

**Comment by olivierpierre** [comment]
Hi Stefan, thanks a lot for the fix.

I tried it on my sample program, as well as on benchmarks that make extensive use of the heap (for example npb DC): the fix worked. However, I noticed that for programs that have a very large BSS section, this section ends up overlapping with `0x3FE00000`, causing a page fault in `initd` (where BSS is zeroed out) when this particular address is accessed.

You can reproduce the issue with the following program:

```C
#include <stdio.h>
#include <stdlib.h>

unsigned int big_bss[512][1024][1024];

int main(void) {
	int i, j, k;

	for(i=0; i<512; i++)
		for(j=0; j<1024; j++)
			for(k=0; k<1024; k++)
				big_bss[i][j][k] = 0;

	return 0;
}
```

**Comment by stlankes** [comment]
Hello @olivierpierre

I think that I fix this issues in the branch devel. Does it work on your system?

Cheers

Stefan

**Comment by olivierpierre** [comment]
Hi @stlankes, yes it works! I successfully ran the test program shown in my previous comment.
Thanks for the fix,
Pierre
